name: Publish

on:
  - push

jobs:
#  release-conda:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-18.04]
#        python-version: [3.8]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build wheels
#        uses: docker://continuumio/miniconda3:4.7.10
#        with:
#          entrypoint: /usr/bin/env
#        env:
#          FIRST_NAME: Mona
#
#  macos-conda-build:
#    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: ["macos-10.14"]
#        python-version: ["3.7"]
#    steps:
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
#      - name: Conda build
#        shell: bash -l {0}
#        run: git clone https://github.com/pyscf/pyscf && conda install -y anaconda-client conda-build && conda build --output-folder . pyscf/conda

  release-pypi-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        run: |
           pip install wheel auditwheel
           git clone https://github.com/pyscf/pyscf
           pip wheel -v --no-deps --no-clean -w ${{ github.workspace }}/wheelhouse ${{ github.workspace }}/pyscf
           auditwheel -v repair $(ls ${{ github.workspace }}/wheelhouse/pyscf-*.whl) --lib-sdir /lib -w ${{ github.workspace }}/mac-wheels
      - name: List available wheels
        run: |
          ls ${{ github.workspace }}/mac-wheels
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          #password: ${{ secrets.PYPI_API_TOKEN }}
          #packages_dir: ${{ github.workspace }}/mac-wheels
          verbose: true
